/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2022-09-12 06:57:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\" />\r\n");
      out.write("    <title>login</title>\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        html {\r\n");
      out.write("            height: 100%;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            background: url(img/amylibrary.jpg);\r\n");
      out.write("            background-repeat: no-repeat;\r\n");
      out.write("            background-size: 100% 100%;\r\n");
      out.write("            -moz-background-size: 100% 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            height: 100%;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #loginDiv {\r\n");
      out.write("            width: 400px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            height: 400px;\r\n");
      out.write("            background-color: rgba(75, 81, 95, 0.3);\r\n");
      out.write("            box-shadow: 7px 7px 17px rgba(52, 56, 66, 0.5);\r\n");
      out.write("            border-radius: 250px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        p {\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("            margin-left: 20px;\r\n");
      out.write("            color: azure;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        input {\r\n");
      out.write("            margin-left: 15px;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            border-style: hidden;\r\n");
      out.write("            height: 30px;\r\n");
      out.write("            width: 140px;\r\n");
      out.write("            background-color: rgba(216, 191, 216, 0.5);\r\n");
      out.write("            outline: none;\r\n");
      out.write("            color: #f0edf3;\r\n");
      out.write("            padding-left: 10px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .button {\r\n");
      out.write("            border-color: cornsilk;\r\n");
      out.write("            background-color: rgba(100, 149, 237, .7);\r\n");
      out.write("            color: aliceblue;\r\n");
      out.write("            border-style: hidden;\r\n");
      out.write("            border-radius: 5px;\r\n");
      out.write("            width: 100px;\r\n");
      out.write("            height: 31px;\r\n");
      out.write("            font-size: 16px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("    <style type=\"text/css\">\r\n");
      out.write("        input::-ms-input-placeholder{text-align: center;}\r\n");
      out.write("        input::-webkit-input-placeholder{text-align: center;}\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<div id=\"loginDiv\">\r\n");
      out.write("    <form action=\"/myLibrary/LoginServlet\" method=\"post\" id=\"form\">\r\n");
      out.write("        <h1 style=\"text-align: center;color: aliceblue;\">LOGIN IN</h1>\r\n");
      out.write("        <div id=\"errorMsg\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${login_msg}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("</div>\r\n");
      out.write("        <p>Username:<input id=\"username\" name=\"username\" type=\"text\"></p>\r\n");
      out.write("\r\n");
      out.write("        <p>Password:<input id=\"password\" name=\"password\" type=\"password\" placeholder=\"密码长度至少为6位\"></p>\r\n");
      out.write("        <div style=\"text-align: center;margin-top: 30px;\">\r\n");
      out.write("            <input type=\"submit\" class=\"button\" value=\"login up\" >\r\n");
      out.write("            <a href=\"register.html\">注册</a>\r\n");
      out.write("        </div>\r\n");
      out.write("    </form>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
